from pydantic import BaseModel, Field
from typing import Optional

class HealthResponse(BaseModel):
    status: str
    message: str

class AgentResponse(BaseModel):
    message: str

class CurrentWeatherUnits(BaseModel):
    """Units for current weather parameters"""

    time: Optional[str] = Field(None, description="Time format unit")
    interval: Optional[str] = Field(None, description="Interval unit")
    temperature_2m: Optional[str] = Field(None, description="Air temperature at 2 meters above ground unit")
    relative_humidity_2m: Optional[str] = Field(None, description="Relative humidity at 2 meters above ground unit")
    dew_point_2m: Optional[str] = Field(None, description="Dew point temperature at 2 meters above ground unit")
    apparent_temperature: Optional[str] = Field(None, description="Apparent temperature unit")
    pressure_msl: Optional[str] = Field(None, description="Atmospheric air pressure reduced to mean sea level unit")
    surface_pressure: Optional[str] = Field(None, description="Atmospheric air pressure at surface unit")
    cloud_cover: Optional[str] = Field(None, description="Total cloud cover unit")
    cloud_cover_low: Optional[str] = Field(None, description="Low level clouds and fog unit")
    cloud_cover_mid: Optional[str] = Field(None, description="Mid level clouds unit")
    cloud_cover_high: Optional[str] = Field(None, description="High level clouds unit")
    wind_speed_10m: Optional[str] = Field(None, description="Wind speed at 10 meters above ground unit")
    wind_speed_80m: Optional[str] = Field(None, description="Wind speed at 80 meters above ground unit")
    wind_speed_120m: Optional[str] = Field(None, description="Wind speed at 120 meters above ground unit")
    wind_speed_180m: Optional[str] = Field(None, description="Wind speed at 180 meters above ground unit")
    wind_direction_10m: Optional[str] = Field(None, description="Wind direction at 10 meters above ground unit")
    wind_direction_80m: Optional[str] = Field(None, description="Wind direction at 80 meters above ground unit")
    wind_direction_120m: Optional[str] = Field(None, description="Wind direction at 120 meters above ground unit")
    wind_direction_180m: Optional[str] = Field(None, description="Wind direction at 180 meters above ground unit")
    wind_gusts_10m: Optional[str] = Field(None, description="Gusts at 10 meters above ground unit")
    shortwave_radiation: Optional[str] = Field(None, description="Shortwave solar radiation unit")
    direct_radiation: Optional[str] = Field(None, description="Direct solar radiation unit")
    direct_normal_irradiance: Optional[str] = Field(None, description="Direct solar radiation on normal plane unit")
    diffuse_radiation: Optional[str] = Field(None, description="Diffuse solar radiation unit")
    global_tilted_irradiance: Optional[str] = Field(None, description="Total radiation received on tilted pane unit")
    vapour_pressure_deficit: Optional[str] = Field(None, description="Vapour Pressure Deficit unit")
    cape: Optional[str] = Field(None, description="Convective available potential energy unit")
    evapotranspiration: Optional[str] = Field(None, description="Evapotranspiration from land surface and plants unit")
    et0_fao_evapotranspiration: Optional[str] = Field(None, description="ET₀ Reference Evapotranspiration unit")
    precipitation: Optional[str] = Field(None, description="Total precipitation unit")
    snowfall: Optional[str] = Field(None, description="Snowfall amount unit")
    precipitation_probability: Optional[str] = Field(None, description="Probability of precipitation unit")
    rain: Optional[str] = Field(None, description="Rain from large scale weather systems unit")
    showers: Optional[str] = Field(None, description="Showers from convective precipitation unit")
    weather_code: Optional[str] = Field(None, description="Weather condition code unit")
    snow_depth: Optional[str] = Field(None, description="Snow depth on the ground unit")
    freezing_level_height: Optional[str] = Field(None, description="Altitude of 0°C level unit")
    visibility: Optional[str] = Field(None, description="Viewing distance unit")
    soil_temperature_0cm: Optional[str] = Field(None, description="Temperature in soil at 0 cm depth unit")
    soil_temperature_6cm: Optional[str] = Field(None, description="Temperature in soil at 6 cm depth unit")
    soil_temperature_18cm: Optional[str] = Field(None, description="Temperature in soil at 18 cm depth unit")
    soil_temperature_54cm: Optional[str] = Field(None, description="Temperature in soil at 54 cm depth unit")
    soil_moisture_0_to_1cm: Optional[str] = Field(None, description="Soil water content at 0-1 cm depth unit")
    soil_moisture_1_to_3cm: Optional[str] = Field(None, description="Soil water content at 1-3 cm depth unit")
    soil_moisture_3_to_9cm: Optional[str] = Field(None, description="Soil water content at 3-9 cm depth unit")
    soil_moisture_9_to_27cm: Optional[str] = Field(None, description="Soil water content at 9-27 cm depth unit")
    soil_moisture_27_to_81cm: Optional[str] = Field(None, description="Soil water content at 27-81 cm depth unit")
    is_day: Optional[str] = Field(None, description="Day/night indicator unit")

class CurrentWeatherData(BaseModel):
    """Current weather data values"""

    time: Optional[str] = Field(None, description="Current time")
    interval: Optional[float] = Field(None, description="Time interval in seconds")
    temperature_2m: Optional[float] = Field(None, description="Air temperature at 2 meters above ground")
    relative_humidity_2m: Optional[float] = Field(None, description="Relative humidity at 2 meters above ground")
    dew_point_2m: Optional[float] = Field(None, description="Dew point temperature at 2 meters above ground")
    apparent_temperature: Optional[float] = Field(None, description="Apparent temperature is the perceived feels-like temperature combining wind chill factor, relative humidity and solar radiation")
    pressure_msl: Optional[float] = Field(None, description="Atmospheric air pressure reduced to mean sea level (msl)")
    surface_pressure: Optional[float] = Field(None, description="Atmospheric air pressure at surface. Surface pressure gets lower with increasing elevation")
    cloud_cover: Optional[float] = Field(None, description="Total cloud cover as an area fraction")
    cloud_cover_low: Optional[float] = Field(None, description="Low level clouds and fog up to 3 km altitude")
    cloud_cover_mid: Optional[float] = Field(None, description="Mid level clouds from 3 to 8 km altitude")
    cloud_cover_high: Optional[float] = Field(None, description="High level clouds from 8 km altitude")
    wind_speed_10m: Optional[float] = Field(None, description="Wind speed at 10 meters above ground. Wind speed on 10 meters is the standard level")
    wind_speed_80m: Optional[float] = Field(None, description="Wind speed at 80 meters above ground")
    wind_speed_120m: Optional[float] = Field(None, description="Wind speed at 120 meters above ground")
    wind_speed_180m: Optional[float] = Field(None, description="Wind speed at 180 meters above ground")
    wind_direction_10m: Optional[float] = Field(None, description="Wind direction at 10 meters above ground")
    wind_direction_80m: Optional[float] = Field(None, description="Wind direction at 80 meters above ground")
    wind_direction_120m: Optional[float] = Field(None, description="Wind direction at 120 meters above ground")
    wind_direction_180m: Optional[float] = Field(None, description="Wind direction at 180 meters above ground")
    wind_gusts_10m: Optional[float] = Field(None, description="Gusts at 10 meters above ground as a maximum of the preceding hour")
    shortwave_radiation: Optional[float] = Field(None, description="Shortwave solar radiation as average of the preceding hour. This is equal to the total global horizontal irradiation")
    direct_radiation: Optional[float] = Field(None, description="Direct solar radiation as average of the preceding hour on the horizontal plane")
    direct_normal_irradiance: Optional[float] = Field(None, description="Direct solar radiation as average of the preceding hour on the normal plane (perpendicular to the sun)")
    diffuse_radiation: Optional[float] = Field(None, description="Diffuse solar radiation as average of the preceding hour")
    global_tilted_irradiance: Optional[float] = Field(None, description="Total radiation received on a tilted pane as average of the preceding hour")
    vapour_pressure_deficit: Optional[float] = Field(None, description="Vapour Pressure Deficit (VPD) in kilopascal (kPa). For high VPD (>1.6), water transpiration of plants increases. For low VPD (<0.4), transpiration decreases")
    cape: Optional[float] = Field(None, description="Convective available potential energy")
    evapotranspiration: Optional[float] = Field(None, description="Evapotranspration from land surface and plants that weather models assumes for this location. Available soil water is considered")
    et0_fao_evapotranspiration: Optional[float] = Field(None, description="ET₀ Reference Evapotranspiration of a well watered grass field. Based on FAO-56 Penman-Monteith equations")
    precipitation: Optional[float] = Field(None, description="Total precipitation (rain, showers, snow) sum of the preceding hour")
    snowfall: Optional[float] = Field(None, description="Snowfall amount of the preceding hour in centimeters. For the water equivalent in millimeter, divide by 7")
    precipitation_probability: Optional[float] = Field(None, description="Probability of precipitation with more than 0.1 mm of the preceding hour")
    rain: Optional[float] = Field(None, description="Rain from large scale weather systems of the preceding hour in millimeter")
    showers: Optional[float] = Field(None, description="Showers from convective precipitation in millimeters from the preceding hour")
    weather_code: Optional[float] = Field(None, description="Weather condition as a numeric code. Follow WMO weather interpretation codes")
    snow_depth: Optional[float] = Field(None, description="Snow depth on the ground")
    freezing_level_height: Optional[float] = Field(None, description="Altitude above sea level of the 0°C level")
    visibility: Optional[float] = Field(None, description="Viewing distance in meters. Influenced by low clouds, humidity and aerosols")
    soil_temperature_0cm: Optional[float] = Field(None, description="Temperature in the soil at 0 cm depth. 0 cm is the surface temperature on land or water surface temperature on water")
    soil_temperature_6cm: Optional[float] = Field(None, description="Temperature in the soil at 6 cm depth")
    soil_temperature_18cm: Optional[float] = Field(None, description="Temperature in the soil at 18 cm depth")
    soil_temperature_54cm: Optional[float] = Field(None, description="Temperature in the soil at 54 cm depth")
    soil_moisture_0_to_1cm: Optional[float] = Field(None, description="Average soil water content as volumetric mixing ratio at 0-1 cm depth")
    soil_moisture_1_to_3cm: Optional[float] = Field(None, description="Average soil water content as volumetric mixing ratio at 1-3 cm depth")
    soil_moisture_3_to_9cm: Optional[float] = Field(None, description="Average soil water content as volumetric mixing ratio at 3-9 cm depth")
    soil_moisture_9_to_27cm: Optional[float] = Field(None, description="Average soil water content as volumetric mixing ratio at 9-27 cm depth")
    soil_moisture_27_to_81cm: Optional[float] = Field(None, description="Average soil water content as volumetric mixing ratio at 27-81 cm depth")
    is_day: Optional[float] = Field(None, description="1 if the current time step has daylight, 0 at night")

class CurrentWeatherResponse(BaseModel):
    """Response model for current weather data from the API"""
    
    latitude: float = Field(..., description="Geographical WGS84 coordinate of the location (latitude)")
    longitude: float = Field(..., description="Geographical WGS84 coordinate of the location (longitude)")
    generationtime_ms: float = Field(..., description="Time taken to generate the response in milliseconds")
    utc_offset_seconds: float = Field(..., description="UTC offset in seconds")
    timezone: str = Field(..., description="Timezone name")
    timezone_abbreviation: str = Field(..., description="Timezone abbreviation")
    elevation: float = Field(..., description="Elevation used for the location in meters")
    current_units: Optional[CurrentWeatherUnits] = Field(None, description="Units for current weather parameters")
    current: Optional[CurrentWeatherData] = Field(None, description="Current weather data values")




